```{r}
dados =  read.csv("Churn.csv", sep = ";", na.strings = "", stringsAsFactors = T)
head(dados)
summary(dados)
```

```{r}
colnames(dados) = c("id","Score","Estado","Genero","Idade","Patrimonio","Saldo","Produtos","TemCartCredito",
                    "Ativo","Salario","Saiu")
head(dados)
```

```{r}
counts = table(dados$Estado)
barplot(counts, main = "Estados", xlab="Estados")

counts = table(dados$Genero)
barplot(counts, main = "Genero", xlab="Genero")

```

```{r}
summary(dados$Score)
boxplot(dados$Score)
hist(dados$Score)
```

```{r}
summary(dados$Idade)
boxplot(dados$Idade)
hist(dados$Idade)
```

```{r}
summary(dados$Saldo)
boxplot(dados$Saldo)
hist(dados$Saldo)
```

```{r}
dados[!complete.cases(dados),]
```

```{r}
summary(dados$Salario)
median(dados$Salario,na.rm = T)
dados[is.na(dados$Salario),]$Salario = median(dados$Salario,na.rm = T)
dados[!complete.cases(dados$Salario),]
```

```{r}
unique(dados$Genero)
summary(dados$Genero)

dados[is.na(dados$Genero),]
```

```{r}
dados[is.na(dados$Genero) | dados$Genero == "M",]$Genero = "Masculino"
dados[dados$Genero == "F"|dados$Genero == "Fem",]$Genero = "Feminino"

summary(dados$Genero)

dados$Genero = factor(dados$Genero)

summary(dados$Genero)

```

```{r}
summary(dados$Idade)

dados[dados$Idade < 0 | dados$Idade >110,]$Idade

dados[is.na(dados$Idade),]

dados[dados$Idade < 0 | dados$Idade >110,]$Idade = median(dados$Idade)

dados[dados$Idade < 0 | dados$Idade >110,]

summary(dados$Idade)
```

```{r}
x = dados[duplicated(dados$id),]
x

dados = dados[!dados$id %in% c(x$id),]
dados[dados$id == x$id,]

x = dados[duplicated(dados$id),]
x
```

```{r}
unique(dados$Estado)
summary(dados$Estado)

dados[!dados$Estado %in% c("RS","SC","PR"),]$Estado = "RS"
summary(dados$Estado)

dados$Estado = factor(dados$Estado)
summary(dados$Estado)
```

```{r}
desv = sd(dados$Salario, na.rm = T)
dados[dados$Salario >= 2 * desv,]$Salario

boxplot(dados$Salario)
x = boxplot(dados$Salario)$out
x

median(dados$Salario)
dados[dados$Salario >= 2 * desv,]$Salario = median(dados$Salario)
dados[dados$Salario >= 2 * desv,]$Salario
```

